name: Build and Deploy Pandoc Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Pandoc
        run: sudo apt-get install pandoc -y

      - name: Create output directory
        run: mkdir -p public

      - name: Convert Markdown to HTML
        run: |
          for file in content/*.md; do
            name=$(basename "$file" .md)
            pandoc "$file" -s -o "public/$name.html" --toc --toc-depth=2
          done
          pandoc index.md -s -o public/index.html --metadata title="Index"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
